name: "ci"
on:
  push:
    branches: [backup, master, sssd-2-7, sssd-2-8]
  pull_request:
    branches: [backup, master, sssd-2-7, sssd-2-8]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  system:
    strategy:
      fail-fast: false
      matrix:
        tag: [fedora-38, rawhide]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout sssd repository
      uses: actions/checkout@v3
      with:
        path: sssd

    - name: Setup containers
      uses: SSSD/sssd-ci-containers/actions/setup@master
      with:
        path: sssd-ci-containers
        tag: ${{ matrix.tag }}
        override: |
          services:
            client:
              image: ${REGISTRY}/ci-client-devel:${TAG}
              shm_size: 4G
              tmpfs:
              - /dev/shm
              volumes:
              - ../sssd:/sssd:rw

    - name: Install system tests dependencies
      shell: bash
      working-directory: ./sssd/src/tests/system
      run: |
        set -ex

        sudo apt-get update

        # Install dependencies for python-ldap
        sudo apt-get install -y libsasl2-dev python3-dev libldap2-dev libssl-dev

        # Virtualenv
        pip3 install virtualenv
        python3 -m venv .venv
        source .venv/bin/activate

        # Install system tests requirements
        pip3 install -r ./requirements.txt

        # Install yq to parse yaml files
        sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        sudo chmod a+x /usr/local/bin/yq

    - name: Remove ad from mhc.yaml
      shell: bash
      working-directory: ./sssd/src/tests/system
      run: |
        yq -i 'del(.domains[0].hosts.[] | select(.role == "ad"))' mhc.yaml

    - name: Run tests
      shell: bash
      working-directory: ./sssd/src/tests/system
      env:
        MH_SSH_DEBUG: ${{ vars.MH_SSH_DEBUG }}
      run: |
        set -ex -o pipefail

        echo MH_SSH_DEBUG=$MH_SSH_DEBUG

        source .venv/bin/activate
        MH_SSH_DEBUG=yes pytest \
          --color=yes \
          --mh-config=./mhc.yaml \
          --mh-log-path=$GITHUB_WORKSPACE/mh.log \
          --mh-artifacts-dir=$GITHUB_WORKSPACE/artifacts \
          -vvv . |& tee $GITHUB_WORKSPACE/pytest.log

    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: ignore
        name: ${{ matrix.tag }}-system
        path: |
          sssd/ci-install-deps.log
          artifacts
          mh.log
          build.log
          install.log
          pytest.log
