name: copr
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
env:
  COPR_ACCOUNT: '@sssd'
  COPR_PROJECT: pr${{ github.event.pull_request.number }}
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      srpm: ${{ steps.srpm.outputs.file }}
      chroots_json: ${{ steps.chroots.outputs.json }}
    permissions:
      contents: read
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
    - name: Build source rpm
      id: srpm
      uses: ./.github/actions/build-srpm
      with:
        version: ${{ env.COPR_PROJECT }}
    - name: Upload source rpm as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.srpm.outputs.file }}
        path: ${{ steps.srpm.outputs.path }}
    - name: Initialize copr actions
      id: copr
      uses: SSSD/action-copr/init@master
      with:
        token: ${{ secrets.COPR_SECRETS }}
    - name: Get copr chroots
      id: chroots
      uses: SSSD/action-copr/filter-chroots@master
      with:
        coprcfg: ${{ secrets.COPR_SECRETS }}
        filter: "fedora-.+-x86_64|centos-stream-9-x86_64"
        exclude: "fedora-eln-.+"
    - name: Create copr project
      uses: SSSD/action-copr/create-project@master
      with:
        coprcfg: ${{ steps.copr.outputs.coprcfg }}
        chroots: ${{ steps.chroots.outputs.list }}
        project: ${{ env.COPR_PROJECT }}
        account: ${{ env.COPR_ACCOUNT }}
    - name: Cancel pending builds
      uses: SSSD/action-copr/cancel-builds@master
      with:
        coprcfg: ${{ steps.copr.outputs.coprcfg }}
        project: ${{ env.COPR_PROJECT }}
        account: ${{ env.COPR_ACCOUNT }}
    - name: Add buildroot repository to CentOS Stream
      env:
        coprcfg: ${{ steps.copr.outputs.coprcfg }}
      run: |
        copr-cli --config "$coprcfg" edit-chroot                                                  \
          --repos 'https://kojihub.stream.centos.org/kojifiles/repos/c9s-build/latest/$basearch/' \
          $COPR_ACCOUNT/$COPR_PROJECT/centos-stream-9-x86_64

  build:
    runs-on: ubuntu-latest
    needs: [prepare]
    strategy:
      matrix:
        chroot: ${{ fromJson(needs.prepare.outputs.chroots_json) }}
      fail-fast: false
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Downlooad source rpm
      uses: actions/download-artifact@v2
      with:
        name: ${{ needs.prepare.outputs.srpm }}
        path: .
    - name: Initialize copr actions
      id: copr
      uses: SSSD/action-copr/init@master
      with:
        token: ${{ secrets.COPR_SECRETS }}
    - name: Build srpm in copr for ${{ matrix.chroot }}
      uses: SSSD/action-copr/submit-build@master
      with:
        coprcfg: ${{ steps.copr.outputs.coprcfg }}
        srpm: ${{ needs.prepare.outputs.srpm }}
        chroots: ${{ matrix.chroot }}
        project: ${{ env.COPR_PROJECT }}
        account: ${{ env.COPR_ACCOUNT }}
