name: pr
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo ${{ github.event.pull_request.head.ref }}
        echo ${{ github.head_ref }}
        echo ${{ github.ref }}