name: Test
on:
  pull_request:
    types:
      - synchronize
jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Success
        run: |
          # Just succeed, as the pull request was updated by this job
          exit 0
